backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'buildings'
    label: 'Buildings'
    folder: 'content/building'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Address', name: 'address', widget: 'string' }
      - { label: 'City', name: 'city', widget: 'string', defalut: 'Chicago' }
      - { label: 'State', name: 'state', widget: 'string', default: 'IL' }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Alt',
          name: 'alt',
          widget: 'string',
          default: 'image of a building',
        }
      - { label: 'Featured Image', name: 'featImage', widget: 'image' }
      - label: 'Gallery'
        name: 'galleryImages'
        widget: 'list'
        fields:
          - { label: 'Image', name: 'imagegal', widget: 'image' }
          - { label: 'Alt Text', name: 'alt', widget: 'string' }
  - name: 'settings'
  - label: 'Settings'
    folder: 'content/building'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Site Title', name: 'site_title', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image' }
      - {
          label: 'Meta Description',
          name: 'meta_description',
          widget: 'text',
          defalut: 'This is a site where you can find luxuray apartments. Contact your agent today',
        }
      - { label: 'Header Image', name: 'header_image', widget: 'image' }
